SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW RR
JOIN
    MEMBER_PROFILE MP
ON
    RR.MEMBER_ID = MP.MEMBER_ID
WHERE
    RR.MEMBER_ID = (
        SELECT MEMBER_ID
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS REVIEW_TOTAL
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY REVIEW_TOTAL DESC
            LIMIT 1
        ) AS TOP_MEMBER
    )
ORDER BY
    RR.REVIEW_DATE ASC,
    RR.REVIEW_TEXT ASC;
